"""

ADLXPybind: Python bindings for AMD ADLX SDK.
"""
from ADLXPybind._adlx_pybind import ADLXGPUHolder
from ADLXPybind._adlx_pybind import ADLXHelper
from ADLXPybind._adlx_pybind import ADLX_DISPLAY_CONNECTOR_TYPE
from ADLXPybind._adlx_pybind import ADLX_DISPLAY_SCAN_TYPE
from ADLXPybind._adlx_pybind import ADLX_DISPLAY_TYPE
from ADLXPybind._adlx_pybind import ADLX_RESULT
from ADLXPybind._adlx_pybind import DisplayListCallBack
from ADLXPybind._adlx_pybind import GPUIterator
from ADLXPybind._adlx_pybind import IADLXDisplay
from ADLXPybind._adlx_pybind import IADLXDisplayChangedHandling
from ADLXPybind._adlx_pybind import IADLXDisplayServices
from ADLXPybind._adlx_pybind import IADLXGPU
from ADLXPybind._adlx_pybind import IADLXGPUList as IADLXGPUListFacade
from ADLXPybind._adlx_pybind import IADLXGPUList
from ADLXPybind._adlx_pybind import IADLXGPUMetrics
from ADLXPybind._adlx_pybind import IADLXGPUMetrics2
from ADLXPybind._adlx_pybind import IADLXGPUMetricsSupport
from ADLXPybind._adlx_pybind import IADLXGPUMetricsSupport2
from ADLXPybind._adlx_pybind import IADLXPerformanceMonitoringServices
from ADLXPybind._adlx_pybind import IADLXSystem
from __future__ import annotations
from . import _adlx_pybind
__all__ = ['ADLXGPUHolder', 'ADLXHelper', 'ADLX_ADL_INIT_ERROR', 'ADLX_ALREADY_ENABLED', 'ADLX_ALREADY_INITIALIZED', 'ADLX_BAD_VER', 'ADLX_DISPLAY_CONNECTOR_TYPE', 'ADLX_DISPLAY_SCAN_TYPE', 'ADLX_DISPLAY_TYPE', 'ADLX_FAIL', 'ADLX_INVALID_ARGS', 'ADLX_INVALID_OBJECT', 'ADLX_NOT_FOUND', 'ADLX_NOT_SUPPORTED', 'ADLX_OK', 'ADLX_ORPHAN_OBJECTS', 'ADLX_RESULT', 'ADLX_TERMINATED', 'ADLX_UNKNOWN_INTERFACE', 'DISPLAY_CONTYPE_COMPOSITE', 'DISPLAY_CONTYPE_CVDONGLE_JPN', 'DISPLAY_CONTYPE_CVDONGLE_NONI2C_JPN', 'DISPLAY_CONTYPE_CVDONGLE_NONI2C_NTSC', 'DISPLAY_CONTYPE_CVDONGLE_NTSC', 'DISPLAY_CONTYPE_DISPLAYPORT', 'DISPLAY_CONTYPE_DVI_D', 'DISPLAY_CONTYPE_DVI_I', 'DISPLAY_CONTYPE_EDP', 'DISPLAY_CONTYPE_HDMI_TYPE_A', 'DISPLAY_CONTYPE_HDMI_TYPE_B', 'DISPLAY_CONTYPE_RCA_3COMPONENT', 'DISPLAY_CONTYPE_SVIDEO', 'DISPLAY_CONTYPE_UNKNOWN', 'DISPLAY_CONTYPE_USB_TYPE_C', 'DISPLAY_CONTYPE_VGA', 'DISPLAY_CONTYPE_WIRELESSDISPLAY', 'DISPLAY_TYPE_COMPONENT_VIDEO', 'DISPLAY_TYPE_DIGITAL_FLAT_PANEL', 'DISPLAY_TYPE_LCD_PANEL', 'DISPLAY_TYPE_MONITOR', 'DISPLAY_TYPE_PROJECTOR', 'DISPLAY_TYPE_TELEVISION', 'DISPLAY_TYPE_UNKOWN', 'DisplayListCallBack', 'GPUIterator', 'IADLXDisplay', 'IADLXDisplayChangedHandling', 'IADLXDisplayServices', 'IADLXGPU', 'IADLXGPUList', 'IADLXGPUListFacade', 'IADLXGPUMetrics', 'IADLXGPUMetrics2', 'IADLXGPUMetricsSupport', 'IADLXGPUMetricsSupport2', 'IADLXPerformanceMonitoringServices', 'IADLXSystem', 'IID_IADLXGPUMetrics2', 'IID_IADLXGPUMetricsSupport2', 'INTERLACED', 'PROGRESSIVE']
ADLX_ADL_INIT_ERROR: _adlx_pybind.ADLX_RESULT  # value = <ADLX_RESULT.ADLX_ADL_INIT_ERROR: 8>
ADLX_ALREADY_ENABLED: _adlx_pybind.ADLX_RESULT  # value = <ADLX_RESULT.ADLX_ALREADY_ENABLED: 1>
ADLX_ALREADY_INITIALIZED: _adlx_pybind.ADLX_RESULT  # value = <ADLX_RESULT.ADLX_ALREADY_INITIALIZED: 2>
ADLX_BAD_VER: _adlx_pybind.ADLX_RESULT  # value = <ADLX_RESULT.ADLX_BAD_VER: 5>
ADLX_FAIL: _adlx_pybind.ADLX_RESULT  # value = <ADLX_RESULT.ADLX_FAIL: 3>
ADLX_INVALID_ARGS: _adlx_pybind.ADLX_RESULT  # value = <ADLX_RESULT.ADLX_INVALID_ARGS: 4>
ADLX_INVALID_OBJECT: _adlx_pybind.ADLX_RESULT  # value = <ADLX_RESULT.ADLX_INVALID_OBJECT: 10>
ADLX_NOT_FOUND: _adlx_pybind.ADLX_RESULT  # value = <ADLX_RESULT.ADLX_NOT_FOUND: 9>
ADLX_NOT_SUPPORTED: _adlx_pybind.ADLX_RESULT  # value = <ADLX_RESULT.ADLX_NOT_SUPPORTED: 12>
ADLX_OK: _adlx_pybind.ADLX_RESULT  # value = <ADLX_RESULT.ADLX_OK: 0>
ADLX_ORPHAN_OBJECTS: _adlx_pybind.ADLX_RESULT  # value = <ADLX_RESULT.ADLX_ORPHAN_OBJECTS: 11>
ADLX_TERMINATED: _adlx_pybind.ADLX_RESULT  # value = <ADLX_RESULT.ADLX_TERMINATED: 7>
ADLX_UNKNOWN_INTERFACE: _adlx_pybind.ADLX_RESULT  # value = <ADLX_RESULT.ADLX_UNKNOWN_INTERFACE: 6>
DISPLAY_CONTYPE_COMPOSITE: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_COMPOSITE: 12>
DISPLAY_CONTYPE_CVDONGLE_JPN: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_CVDONGLE_JPN: 5>
DISPLAY_CONTYPE_CVDONGLE_NONI2C_JPN: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_CVDONGLE_NONI2C_JPN: 6>
DISPLAY_CONTYPE_CVDONGLE_NONI2C_NTSC: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_CVDONGLE_NONI2C_NTSC: 7>
DISPLAY_CONTYPE_CVDONGLE_NTSC: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_CVDONGLE_NTSC: 4>
DISPLAY_CONTYPE_DISPLAYPORT: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_DISPLAYPORT: 14>
DISPLAY_CONTYPE_DVI_D: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_DVI_D: 2>
DISPLAY_CONTYPE_DVI_I: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_DVI_I: 3>
DISPLAY_CONTYPE_EDP: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_EDP: 15>
DISPLAY_CONTYPE_HDMI_TYPE_A: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_HDMI_TYPE_A: 9>
DISPLAY_CONTYPE_HDMI_TYPE_B: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_HDMI_TYPE_B: 10>
DISPLAY_CONTYPE_RCA_3COMPONENT: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_RCA_3COMPONENT: 13>
DISPLAY_CONTYPE_SVIDEO: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_SVIDEO: 11>
DISPLAY_CONTYPE_UNKNOWN: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_UNKNOWN: 0>
DISPLAY_CONTYPE_USB_TYPE_C: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_USB_TYPE_C: 17>
DISPLAY_CONTYPE_VGA: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_VGA: 1>
DISPLAY_CONTYPE_WIRELESSDISPLAY: _adlx_pybind.ADLX_DISPLAY_CONNECTOR_TYPE  # value = <ADLX_DISPLAY_CONNECTOR_TYPE.DISPLAY_CONTYPE_WIRELESSDISPLAY: 16>
DISPLAY_TYPE_COMPONENT_VIDEO: _adlx_pybind.ADLX_DISPLAY_TYPE  # value = <ADLX_DISPLAY_TYPE.DISPLAY_TYPE_COMPONENT_VIDEO: 5>
DISPLAY_TYPE_DIGITAL_FLAT_PANEL: _adlx_pybind.ADLX_DISPLAY_TYPE  # value = <ADLX_DISPLAY_TYPE.DISPLAY_TYPE_DIGITAL_FLAT_PANEL: 4>
DISPLAY_TYPE_LCD_PANEL: _adlx_pybind.ADLX_DISPLAY_TYPE  # value = <ADLX_DISPLAY_TYPE.DISPLAY_TYPE_LCD_PANEL: 3>
DISPLAY_TYPE_MONITOR: _adlx_pybind.ADLX_DISPLAY_TYPE  # value = <ADLX_DISPLAY_TYPE.DISPLAY_TYPE_MONITOR: 1>
DISPLAY_TYPE_PROJECTOR: _adlx_pybind.ADLX_DISPLAY_TYPE  # value = <ADLX_DISPLAY_TYPE.DISPLAY_TYPE_PROJECTOR: 6>
DISPLAY_TYPE_TELEVISION: _adlx_pybind.ADLX_DISPLAY_TYPE  # value = <ADLX_DISPLAY_TYPE.DISPLAY_TYPE_TELEVISION: 2>
DISPLAY_TYPE_UNKOWN: _adlx_pybind.ADLX_DISPLAY_TYPE  # value = <ADLX_DISPLAY_TYPE.DISPLAY_TYPE_UNKOWN: 0>
IID_IADLXGPUMetrics2: str = 'IADLXGPUMetrics2'
IID_IADLXGPUMetricsSupport2: str = 'IADLXGPUMetricsSupport2'
INTERLACED: _adlx_pybind.ADLX_DISPLAY_SCAN_TYPE  # value = <ADLX_DISPLAY_SCAN_TYPE.INTERLACED: 1>
PROGRESSIVE: _adlx_pybind.ADLX_DISPLAY_SCAN_TYPE  # value = <ADLX_DISPLAY_SCAN_TYPE.PROGRESSIVE: 0>
__author__: str = 'sfinktah@github.spamtrak.org'
__license__: str = 'MIT'
__version__: str = '1.0.1'
