name: Publish Windows Wheel to PyPI

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Windows Wheel"]
    types:
      - completed

permissions:
  contents: read

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Windows wheel
        uses: actions/download-artifact@v4
        with:
          name: windows-wheel
          path: dist

      - name: Publish Windows wheel to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/

      # Optional: Classic API Token (if not using Trusted Publishing)
      - name: Publish using Twine (Classic API Token)
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m pip install --upgrade twine
          twine upload dist/*.whl
